"""Declarative base and model registry for SQLAlchemy."""

from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Base class for all ORM models."""


# Import every feature slice's models module below when it is introduced.
# Alembic only discovers models imported into this metadata registry; omitting an
# import can result in empty or destructive autogenerated migrations.
import app.auth.models as _auth_models  # noqa: E402, F401
