"""Declarative base and model registry for SQLAlchemy."""

from sqlalchemy.orm import DeclarativeBase

from app.db.mixins import (
    SoftDeleteMixin,
    TenantScopedMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
)


class Base(DeclarativeBase):
    """Base class for all ORM models."""


class TimestampedModel(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """UUID primary key and timestamps. Use for rows that are not tenant-scoped."""

    __abstract__ = True


class TenantModel(UUIDPrimaryKeyMixin, TenantScopedMixin, TimestampMixin, Base):
    """Default tenant-owned row without soft-delete (identity, child, and line rows)."""

    __abstract__ = True


class SoftDeleteTenantModel(SoftDeleteMixin, TenantModel):
    """Default for tenant-owned masters and documents that must support soft-delete."""

    __abstract__ = True


# Import every feature slice's models module below when it is introduced.
# Alembic only discovers models imported into this metadata registry; omitting an
# import can result in empty or destructive autogenerated migrations.
import app.auth.models as _auth_models  # noqa: E402, F401
import app.common.attachments.models as _attachments  # noqa: E402, F401
import app.common.models.audit_log as _audit_log  # noqa: E402, F401
import app.crm.contacts.models as _contacts  # noqa: E402, F401
import app.crm.customers.models as _customers  # noqa: E402, F401
import app.erp.accounting.models as _accounting  # noqa: E402, F401
import app.erp.exchange_rates.models as _exchange_rates  # noqa: E402, F401
import app.erp.quotation.models as _quotation  # noqa: E402, F401
import app.inventory_management.categories.models as _categories  # noqa: E402, F401
import app.inventory_management.price_lists.models as _price_lists  # noqa: E402, F401
import app.inventory_management.products.models as _products  # noqa: E402, F401
import app.inventory_management.units.models as _units  # noqa: E402, F401
import app.inventory_management.warehouses.models as _warehouses  # noqa: E402, F401
