"""Static ISO 4217 currency catalog used when seeding a tenant.

Current alphabetic codes only (no withdrawn codes). Precious metals (XAU, XAG,
XPT, XPD) and placeholders (XXX, XTS) are omitted. Regional tenders (EUR, XCD,
XOF, XAF, XPF) are included. Codes with no ISO minor unit are omitted because
decimal_places cannot be taken from the standard.
"""

from typing import NamedTuple

BASE_CURRENCY_CODE = "AED"


class CurrencyCatalogEntry(NamedTuple):
    code: str
    name: str
    symbol: str
    decimal_places: int


ISO_4217_CURRENCIES: tuple[CurrencyCatalogEntry, ...] = (
    CurrencyCatalogEntry("AED", "UAE Dirham", "د.إ", 2),
    CurrencyCatalogEntry("AFN", "Afghan Afghani", "؋", 2),
    CurrencyCatalogEntry("ALL", "Albanian Lek", "ALL", 2),
    CurrencyCatalogEntry("AMD", "Armenian Dram", "֏", 2),
    CurrencyCatalogEntry("AOA", "Angolan Kwanza", "AOA", 2),
    CurrencyCatalogEntry("ARS", "Argentine Peso", "ARS", 2),
    CurrencyCatalogEntry("AUD", "Australian Dollar", "A$", 2),
    CurrencyCatalogEntry("AWG", "Aruban Florin", "AWG", 2),
    CurrencyCatalogEntry("AZN", "Azerbaijani Manat", "₼", 2),
    CurrencyCatalogEntry("BAM", "Bosnia and Herzegovina Convertible Mark", "BAM", 2),
    CurrencyCatalogEntry("BBD", "Barbados Dollar", "BBD", 2),
    CurrencyCatalogEntry("BDT", "Bangladeshi Taka", "৳", 2),
    CurrencyCatalogEntry("BHD", "Bahraini Dinar", "د.ب", 3),
    CurrencyCatalogEntry("BIF", "Burundian Franc", "BIF", 0),
    CurrencyCatalogEntry("BMD", "Bermudian Dollar", "BMD", 2),
    CurrencyCatalogEntry("BND", "Brunei Dollar", "BND", 2),
    CurrencyCatalogEntry("BOB", "Boliviano", "BOB", 2),
    CurrencyCatalogEntry("BOV", "Bolivian Mvdol", "BOV", 2),
    CurrencyCatalogEntry("BRL", "Brazilian Real", "R$", 2),
    CurrencyCatalogEntry("BSD", "Bahamian Dollar", "BSD", 2),
    CurrencyCatalogEntry("BTN", "Bhutanese Ngultrum", "BTN", 2),
    CurrencyCatalogEntry("BWP", "Botswana Pula", "BWP", 2),
    CurrencyCatalogEntry("BYN", "Belarusian Ruble", "Br", 2),
    CurrencyCatalogEntry("BZD", "Belize Dollar", "BZD", 2),
    CurrencyCatalogEntry("CAD", "Canadian Dollar", "C$", 2),
    CurrencyCatalogEntry("CDF", "Congolese Franc", "CDF", 2),
    CurrencyCatalogEntry("CHE", "WIR Euro", "CHE", 2),
    CurrencyCatalogEntry("CHF", "Swiss Franc", "Fr", 2),
    CurrencyCatalogEntry("CHW", "WIR Franc", "CHW", 2),
    CurrencyCatalogEntry("CLF", "Unidad de Fomento", "CLF", 4),
    CurrencyCatalogEntry("CLP", "Chilean Peso", "CLP", 0),
    CurrencyCatalogEntry("CNY", "Chinese Yuan", "¥", 2),
    CurrencyCatalogEntry("COP", "Colombian Peso", "COP", 2),
    CurrencyCatalogEntry("COU", "Unidad de Valor Real", "COU", 2),
    CurrencyCatalogEntry("CRC", "Costa Rican Colon", "₡", 2),
    CurrencyCatalogEntry("CUP", "Cuban Peso", "CUP", 2),
    CurrencyCatalogEntry("CVE", "Cape Verdean Escudo", "CVE", 2),
    CurrencyCatalogEntry("CZK", "Czech Koruna", "Kč", 2),
    CurrencyCatalogEntry("DJF", "Djiboutian Franc", "DJF", 0),
    CurrencyCatalogEntry("DKK", "Danish Krone", "kr", 2),
    CurrencyCatalogEntry("DOP", "Dominican Peso", "DOP", 2),
    CurrencyCatalogEntry("DZD", "Algerian Dinar", "د.ج", 2),
    CurrencyCatalogEntry("EGP", "Egyptian Pound", "E£", 2),
    CurrencyCatalogEntry("ERN", "Eritrean Nakfa", "ERN", 2),
    CurrencyCatalogEntry("ETB", "Ethiopian Birr", "ETB", 2),
    CurrencyCatalogEntry("EUR", "Euro", "€", 2),
    CurrencyCatalogEntry("FJD", "Fiji Dollar", "FJD", 2),
    CurrencyCatalogEntry("FKP", "Falkland Islands Pound", "£", 2),
    CurrencyCatalogEntry("GBP", "Pound Sterling", "£", 2),
    CurrencyCatalogEntry("GEL", "Georgian Lari", "₾", 2),
    CurrencyCatalogEntry("GHS", "Ghanaian Cedi", "₵", 2),
    CurrencyCatalogEntry("GIP", "Gibraltar Pound", "£", 2),
    CurrencyCatalogEntry("GMD", "Gambian Dalasi", "GMD", 2),
    CurrencyCatalogEntry("GNF", "Guinean Franc", "GNF", 0),
    CurrencyCatalogEntry("GTQ", "Guatemalan Quetzal", "GTQ", 2),
    CurrencyCatalogEntry("GYD", "Guyanese Dollar", "GYD", 2),
    CurrencyCatalogEntry("HKD", "Hong Kong Dollar", "HK$", 2),
    CurrencyCatalogEntry("HNL", "Honduran Lempira", "HNL", 2),
    CurrencyCatalogEntry("HTG", "Haitian Gourde", "HTG", 2),
    CurrencyCatalogEntry("HUF", "Hungarian Forint", "Ft", 2),
    CurrencyCatalogEntry("IDR", "Indonesian Rupiah", "Rp", 2),
    CurrencyCatalogEntry("ILS", "Israeli New Shekel", "₪", 2),
    CurrencyCatalogEntry("INR", "Indian Rupee", "₹", 2),
    CurrencyCatalogEntry("IQD", "Iraqi Dinar", "د.ع", 3),
    CurrencyCatalogEntry("IRR", "Iranian Rial", "﷼", 2),
    CurrencyCatalogEntry("ISK", "Icelandic Krona", "ISK", 0),
    CurrencyCatalogEntry("JMD", "Jamaican Dollar", "JMD", 2),
    CurrencyCatalogEntry("JOD", "Jordanian Dinar", "د.ا", 3),
    CurrencyCatalogEntry("JPY", "Japanese Yen", "¥", 0),
    CurrencyCatalogEntry("KES", "Kenyan Shilling", "KES", 2),
    CurrencyCatalogEntry("KGS", "Kyrgyzstani Som", "KGS", 2),
    CurrencyCatalogEntry("KHR", "Cambodian Riel", "៛", 2),
    CurrencyCatalogEntry("KMF", "Comorian Franc", "KMF", 0),
    CurrencyCatalogEntry("KPW", "North Korean Won", "₩", 2),
    CurrencyCatalogEntry("KRW", "South Korean Won", "₩", 0),
    CurrencyCatalogEntry("KWD", "Kuwaiti Dinar", "د.ك", 3),
    CurrencyCatalogEntry("KYD", "Cayman Islands Dollar", "KYD", 2),
    CurrencyCatalogEntry("KZT", "Kazakhstani Tenge", "₸", 2),
    CurrencyCatalogEntry("LAK", "Lao Kip", "₭", 2),
    CurrencyCatalogEntry("LBP", "Lebanese Pound", "ل.ل", 2),
    CurrencyCatalogEntry("LKR", "Sri Lankan Rupee", "LKR", 2),
    CurrencyCatalogEntry("LRD", "Liberian Dollar", "LRD", 2),
    CurrencyCatalogEntry("LSL", "Lesotho Loti", "LSL", 2),
    CurrencyCatalogEntry("LYD", "Libyan Dinar", "د.ل", 3),
    CurrencyCatalogEntry("MAD", "Moroccan Dirham", "د.م.", 2),
    CurrencyCatalogEntry("MDL", "Moldovan Leu", "MDL", 2),
    CurrencyCatalogEntry("MGA", "Malagasy Ariary", "MGA", 2),
    CurrencyCatalogEntry("MKD", "Macedonian Denar", "MKD", 2),
    CurrencyCatalogEntry("MMK", "Myanmar Kyat", "MMK", 2),
    CurrencyCatalogEntry("MNT", "Mongolian Tugrik", "₮", 2),
    CurrencyCatalogEntry("MOP", "Macanese Pataca", "MOP", 2),
    CurrencyCatalogEntry("MRU", "Mauritanian Ouguiya", "MRU", 2),
    CurrencyCatalogEntry("MUR", "Mauritian Rupee", "MUR", 2),
    CurrencyCatalogEntry("MVR", "Maldivian Rufiyaa", "MVR", 2),
    CurrencyCatalogEntry("MWK", "Malawian Kwacha", "MWK", 2),
    CurrencyCatalogEntry("MXN", "Mexican Peso", "MX$", 2),
    CurrencyCatalogEntry("MXV", "Mexican UDI", "MXV", 2),
    CurrencyCatalogEntry("MYR", "Malaysian Ringgit", "RM", 2),
    CurrencyCatalogEntry("MZN", "Mozambican Metical", "MZN", 2),
    CurrencyCatalogEntry("NAD", "Namibian Dollar", "NAD", 2),
    CurrencyCatalogEntry("NGN", "Nigerian Naira", "₦", 2),
    CurrencyCatalogEntry("NIO", "Nicaraguan Cordoba", "NIO", 2),
    CurrencyCatalogEntry("NOK", "Norwegian Krone", "kr", 2),
    CurrencyCatalogEntry("NPR", "Nepalese Rupee", "NPR", 2),
    CurrencyCatalogEntry("NZD", "New Zealand Dollar", "NZ$", 2),
    CurrencyCatalogEntry("OMR", "Omani Rial", "ر.ع.", 3),
    CurrencyCatalogEntry("PAB", "Panamanian Balboa", "PAB", 2),
    CurrencyCatalogEntry("PEN", "Peruvian Sol", "PEN", 2),
    CurrencyCatalogEntry("PGK", "Papua New Guinean Kina", "PGK", 2),
    CurrencyCatalogEntry("PHP", "Philippine Peso", "₱", 2),
    CurrencyCatalogEntry("PKR", "Pakistani Rupee", "PKR", 2),
    CurrencyCatalogEntry("PLN", "Polish Zloty", "zł", 2),
    CurrencyCatalogEntry("PYG", "Paraguayan Guarani", "₲", 0),
    CurrencyCatalogEntry("QAR", "Qatari Riyal", "ر.ق", 2),
    CurrencyCatalogEntry("RON", "Romanian Leu", "RON", 2),
    CurrencyCatalogEntry("RSD", "Serbian Dinar", "RSD", 2),
    CurrencyCatalogEntry("RUB", "Russian Ruble", "₽", 2),
    CurrencyCatalogEntry("RWF", "Rwandan Franc", "RWF", 0),
    CurrencyCatalogEntry("SAR", "Saudi Riyal", "ر.س", 2),
    CurrencyCatalogEntry("SBD", "Solomon Islands Dollar", "SBD", 2),
    CurrencyCatalogEntry("SCR", "Seychelles Rupee", "SCR", 2),
    CurrencyCatalogEntry("SDG", "Sudanese Pound", "SDG", 2),
    CurrencyCatalogEntry("SEK", "Swedish Krona", "kr", 2),
    CurrencyCatalogEntry("SGD", "Singapore Dollar", "S$", 2),
    CurrencyCatalogEntry("SHP", "Saint Helena Pound", "£", 2),
    CurrencyCatalogEntry("SLE", "Sierra Leonean Leone", "SLE", 2),
    CurrencyCatalogEntry("SOS", "Somali Shilling", "SOS", 2),
    CurrencyCatalogEntry("SRD", "Surinamese Dollar", "SRD", 2),
    CurrencyCatalogEntry("SSP", "South Sudanese Pound", "SSP", 2),
    CurrencyCatalogEntry("STN", "São Tomé and Príncipe Dobra", "STN", 2),
    CurrencyCatalogEntry("SVC", "Salvadoran Colon", "SVC", 2),
    CurrencyCatalogEntry("SYP", "Syrian Pound", "SYP", 2),
    CurrencyCatalogEntry("SZL", "Swazi Lilangeni", "SZL", 2),
    CurrencyCatalogEntry("THB", "Thai Baht", "฿", 2),
    CurrencyCatalogEntry("TJS", "Tajikistani Somoni", "TJS", 2),
    CurrencyCatalogEntry("TMT", "Turkmenistan Manat", "TMT", 2),
    CurrencyCatalogEntry("TND", "Tunisian Dinar", "د.ت", 3),
    CurrencyCatalogEntry("TOP", "Tongan Paʻanga", "TOP", 2),
    CurrencyCatalogEntry("TRY", "Turkish Lira", "₺", 2),
    CurrencyCatalogEntry("TTD", "Trinidad and Tobago Dollar", "TTD", 2),
    CurrencyCatalogEntry("TWD", "New Taiwan Dollar", "NT$", 2),
    CurrencyCatalogEntry("TZS", "Tanzanian Shilling", "TZS", 2),
    CurrencyCatalogEntry("UAH", "Ukrainian Hryvnia", "₴", 2),
    CurrencyCatalogEntry("UGX", "Ugandan Shilling", "UGX", 0),
    CurrencyCatalogEntry("USD", "US Dollar", "$", 2),
    CurrencyCatalogEntry("USN", "US Dollar Next Day", "USN", 2),
    CurrencyCatalogEntry("UYI", "Uruguay Peso en Unidades Indexadas", "UYI", 0),
    CurrencyCatalogEntry("UYU", "Uruguayan Peso", "UYU", 2),
    CurrencyCatalogEntry("UYW", "Unidad Previsional", "UYW", 4),
    CurrencyCatalogEntry("UZS", "Uzbekistani Som", "UZS", 2),
    CurrencyCatalogEntry("VED", "Venezuelan Digital Bolívar", "VED", 2),
    CurrencyCatalogEntry("VES", "Venezuelan Sovereign Bolívar", "VES", 2),
    CurrencyCatalogEntry("VND", "Vietnamese Dong", "₫", 0),
    CurrencyCatalogEntry("VUV", "Vanuatu Vatu", "VUV", 0),
    CurrencyCatalogEntry("WST", "Samoan Tala", "WST", 2),
    CurrencyCatalogEntry("XAD", "Arab Accounting Dinar", "XAD", 2),
    CurrencyCatalogEntry("XAF", "CFA Franc BEAC", "XAF", 0),
    CurrencyCatalogEntry("XCD", "East Caribbean Dollar", "EC$", 2),
    CurrencyCatalogEntry("XCG", "Caribbean Guilder", "XCG", 2),
    CurrencyCatalogEntry("XOF", "CFA Franc BCEAO", "XOF", 0),
    CurrencyCatalogEntry("XPF", "CFP Franc", "XPF", 0),
    CurrencyCatalogEntry("YER", "Yemeni Rial", "﷼", 2),
    CurrencyCatalogEntry("ZAR", "South African Rand", "R", 2),
    CurrencyCatalogEntry("ZMW", "Zambian Kwacha", "ZMW", 2),
    CurrencyCatalogEntry("ZWG", "Zimbabwe Gold", "ZWG", 2),
)
