"""Stable logical ERP enums.

These are application-level strings, not PostgreSQL enum declarations.
"""

from enum import StrEnum


class DocumentStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class QuotationStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    PARTIALLY_CONVERTED = "PARTIALLY_CONVERTED"
    CONVERTED = "CONVERTED"


class SalesOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONFIRMED = "CONFIRMED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class PurchaseOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ISSUED = "ISSUED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class ProformaInvoiceStatus(StrEnum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    CONFIRMED = "CONFIRMED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    PARTIALLY_CONVERTED = "PARTIALLY_CONVERTED"
    CONVERTED = "CONVERTED"


class PaymentMilestoneTrigger(StrEnum):
    ON_CONFIRMATION = "ON_CONFIRMATION"
    BEFORE_SHIPMENT = "BEFORE_SHIPMENT"
    ON_BL_COPY = "ON_BL_COPY"
    ON_ARRIVAL = "ON_ARRIVAL"
    NET_DAYS = "NET_DAYS"


class Incoterm(StrEnum):
    EXW = "EXW"
    FCA = "FCA"
    FAS = "FAS"
    FOB = "FOB"
    CFR = "CFR"
    CIF = "CIF"
    CPT = "CPT"
    CIP = "CIP"
    DAP = "DAP"
    DPU = "DPU"
    DDP = "DDP"


class FulfillmentStatus(StrEnum):
    NOT_DELIVERED = "NOT_DELIVERED"
    PARTIALLY_DELIVERED = "PARTIALLY_DELIVERED"
    DELIVERED = "DELIVERED"


class ReceiptStatus(StrEnum):
    NOT_RECEIVED = "NOT_RECEIVED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    RECEIVED = "RECEIVED"


class BillingStatus(StrEnum):
    NOT_INVOICED = "NOT_INVOICED"
    PARTIALLY_INVOICED = "PARTIALLY_INVOICED"
    INVOICED = "INVOICED"


class PaymentStatus(StrEnum):
    UNPAID = "UNPAID"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"


class CogsStatus(StrEnum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    POSTED = "POSTED"


class InvoiceDocumentStatus(StrEnum):
    DRAFT = "DRAFT"
    POSTED = "POSTED"
    CANCELLED = "CANCELLED"


class BillType(StrEnum):
    GOODS = "GOODS"
    EXPENSE = "EXPENSE"
    IMPORT = "IMPORT"


class PurchaseInvoiceLineType(StrEnum):
    PRODUCT = "PRODUCT"
    EXPENSE = "EXPENSE"


class ExpenseCategory(StrEnum):
    FREIGHT = "FREIGHT"
    CUSTOMS_DUTY = "CUSTOMS_DUTY"
    INSURANCE = "INSURANCE"
    CLEARING = "CLEARING"
    INSPECTION = "INSPECTION"
    OTHER = "OTHER"


class LandedCostAllocationMethod(StrEnum):
    VALUE = "VALUE"
    WEIGHT = "WEIGHT"
    QUANTITY = "QUANTITY"


class CreditNoteReason(StrEnum):
    GOODS_RETURNED = "GOODS_RETURNED"
    PRICE_ADJUSTMENT = "PRICE_ADJUSTMENT"
    SHORT_SHIPMENT = "SHORT_SHIPMENT"
    QUALITY_CLAIM = "QUALITY_CLAIM"
    CANCELLATION = "CANCELLATION"


class DebitNoteReason(StrEnum):
    GOODS_REJECTED = "GOODS_REJECTED"
    PRICE_ADJUSTMENT = "PRICE_ADJUSTMENT"
    SHORT_RECEIPT = "SHORT_RECEIPT"
    QUALITY_CLAIM = "QUALITY_CLAIM"


class TaxTreatment(StrEnum):
    REGISTERED = "REGISTERED"
    UNREGISTERED = "UNREGISTERED"
    EXPORT = "EXPORT"
    GCC = "GCC"
    EXEMPT = "EXEMPT"


class TaxCategory(StrEnum):
    STANDARD = "STANDARD"
    ZERO_RATED = "ZERO_RATED"
    EXEMPT = "EXEMPT"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class PlaceOfSupply(StrEnum):
    ABU_DHABI = "ABU_DHABI"
    DUBAI = "DUBAI"
    SHARJAH = "SHARJAH"
    AJMAN = "AJMAN"
    UMM_AL_QUWAIN = "UMM_AL_QUWAIN"
    RAS_AL_KHAIMAH = "RAS_AL_KHAIMAH"
    FUJAIRAH = "FUJAIRAH"
    OUTSIDE_UAE = "OUTSIDE_UAE"


class DiscountType(StrEnum):
    PERCENTAGE = "PERCENTAGE"
    AMOUNT = "AMOUNT"


class PriceListType(StrEnum):
    PERCENT = "PERCENT"
    CUSTOM_RATES = "CUSTOM_RATES"


class DocumentType(StrEnum):
    QUOTATION = "QUOTATION"
    SALES_ORDER = "SALES_ORDER"
    DELIVERY_NOTE = "DELIVERY_NOTE"
    SALES_INVOICE = "SALES_INVOICE"
    CREDIT_NOTE = "CREDIT_NOTE"
    PURCHASE_ORDER = "PURCHASE_ORDER"
    GOODS_RECEIPT = "GOODS_RECEIPT"
    PURCHASE_INVOICE = "PURCHASE_INVOICE"
    DEBIT_NOTE = "DEBIT_NOTE"
    STOCK_TRANSFER = "STOCK_TRANSFER"
    STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
    PROFORMA_INVOICE = "PROFORMA_INVOICE"
    QUALITY_INSPECTION = "QUALITY_INSPECTION"
    PACKAGE = "PACKAGE"
    SHIPMENT = "SHIPMENT"
    SALES_RETURN = "SALES_RETURN"
    JOURNAL_ENTRY = "JOURNAL_ENTRY"
    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"
    SUPPLIER_PAYMENT = "SUPPLIER_PAYMENT"
    LANDED_COST = "LANDED_COST"


class StockDocumentStatus(StrEnum):
    DRAFT = "DRAFT"
    POSTED = "POSTED"
    CANCELLED = "CANCELLED"


class CostingMethod(StrEnum):
    FIFO = "FIFO"


class AccountType(StrEnum):
    ASSET = "ASSET"
    LIABILITY = "LIABILITY"
    EQUITY = "EQUITY"
    INCOME = "INCOME"
    EXPENSE = "EXPENSE"


class AccountSubtype(StrEnum):
    BANK = "BANK"
    CASH = "CASH"
    ACCOUNTS_RECEIVABLE = "ACCOUNTS_RECEIVABLE"
    ACCOUNTS_PAYABLE = "ACCOUNTS_PAYABLE"
    STOCK = "STOCK"
    FIXED_ASSET = "FIXED_ASSET"
    OTHER_CURRENT_ASSET = "OTHER_CURRENT_ASSET"
    OTHER_CURRENT_LIABILITY = "OTHER_CURRENT_LIABILITY"
    TAX_PAYABLE = "TAX_PAYABLE"
    TAX_RECEIVABLE = "TAX_RECEIVABLE"
    EQUITY = "EQUITY"
    INCOME = "INCOME"
    OTHER_INCOME = "OTHER_INCOME"
    COGS = "COGS"
    EXPENSE = "EXPENSE"
    OTHER_EXPENSE = "OTHER_EXPENSE"


class AccountSystemRole(StrEnum):
    ACCOUNTS_RECEIVABLE = "ACCOUNTS_RECEIVABLE"
    ACCOUNTS_PAYABLE = "ACCOUNTS_PAYABLE"
    SALES_REVENUE = "SALES_REVENUE"
    SALES_RETURNS = "SALES_RETURNS"
    PURCHASES = "PURCHASES"
    INVENTORY = "INVENTORY"
    COGS = "COGS"
    INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT"
    STOCK_SCRAP = "STOCK_SCRAP"
    VAT_OUTPUT = "VAT_OUTPUT"
    VAT_INPUT = "VAT_INPUT"
    VAT_RCM_OUTPUT = "VAT_RCM_OUTPUT"
    VAT_RCM_INPUT = "VAT_RCM_INPUT"
    CUSTOMS_DUTY = "CUSTOMS_DUTY"
    FREIGHT_IN = "FREIGHT_IN"
    PURCHASE_PRICE_VARIANCE = "PURCHASE_PRICE_VARIANCE"
    LANDED_COST_VARIANCE = "LANDED_COST_VARIANCE"
    ADVANCE_FROM_CUSTOMER = "ADVANCE_FROM_CUSTOMER"
    ADVANCE_TO_SUPPLIER = "ADVANCE_TO_SUPPLIER"
    FX_GAIN_LOSS = "FX_GAIN_LOSS"
    ROUND_OFF = "ROUND_OFF"
    GOODS_RECEIVED_NOT_INVOICED = "GOODS_RECEIVED_NOT_INVOICED"
    SHIPPING_INCOME = "SHIPPING_INCOME"
    OTHER_CHARGES = "OTHER_CHARGES"
    RETAINED_EARNINGS = "RETAINED_EARNINGS"
    OPENING_BALANCE_EQUITY = "OPENING_BALANCE_EQUITY"
    CASH_ON_HAND = "CASH_ON_HAND"
    BANK = "BANK"
    BANK_CHARGES = "BANK_CHARGES"
    SUSPENSE = "SUSPENSE"


class JournalEntryStatus(StrEnum):
    DRAFT = "DRAFT"
    POSTED = "POSTED"
    CANCELLED = "CANCELLED"


class JournalType(StrEnum):
    MANUAL = "MANUAL"
    OPENING_BALANCE = "OPENING_BALANCE"
    SYSTEM = "SYSTEM"
    REVERSAL = "REVERSAL"


class PartyType(StrEnum):
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"


class QualityInspectionStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    CANCELLED = "CANCELLED"


class QcStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    CLEARED = "CLEARED"


class QcDisposition(StrEnum):
    RETURN_TO_SUPPLIER = "RETURN_TO_SUPPLIER"
    SCRAP = "SCRAP"
    REWORK_RELEASE = "REWORK_RELEASE"


class PackageStatus(StrEnum):
    DRAFT = "DRAFT"
    PACKED = "PACKED"
    CANCELLED = "CANCELLED"


class ShipmentStatus(StrEnum):
    DRAFT = "DRAFT"
    DISPATCHED = "DISPATCHED"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class TransportMode(StrEnum):
    SEA = "SEA"
    AIR = "AIR"
    ROAD = "ROAD"
    RAIL = "RAIL"
    COURIER = "COURIER"


class SalesReturnReason(StrEnum):
    DAMAGED_IN_TRANSIT = "DAMAGED_IN_TRANSIT"
    WRONG_ITEM_SHIPPED = "WRONG_ITEM_SHIPPED"
    QUALITY_REJECTION = "QUALITY_REJECTION"
    CUSTOMER_CANCELLATION = "CUSTOMER_CANCELLATION"
    SHORT_SHIPMENT = "SHORT_SHIPMENT"
    OTHER = "OTHER"


class ReturnDisposition(StrEnum):
    RESTOCK = "RESTOCK"
    QC_HOLD = "QC_HOLD"
    SCRAP = "SCRAP"


class StockAdjustmentReason(StrEnum):
    OPENING_STOCK = "OPENING_STOCK"
    COUNT = "COUNT"
    DAMAGE = "DAMAGE"
    FOUND = "FOUND"
    OTHER = "OTHER"


class CompanyType(StrEnum):
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"
    BOTH = "BOTH"
    OTHER = "OTHER"


class ItemType(StrEnum):
    PRODUCT = "PRODUCT"
    SERVICE = "SERVICE"


class PaymentMethod(StrEnum):
    BANK = "BANK"
    CASH = "CASH"
    UPI = "UPI"
    CREDIT_CARD = "CREDIT_CARD"
    DEBIT_CARD = "DEBIT_CARD"
    CHEQUE = "CHEQUE"
    ONLINE = "ONLINE"
    TT = "TT"
    OTHER = "OTHER"


class CreditLimitPolicy(StrEnum):
    OFF = "OFF"
    WARN = "WARN"
    BLOCK = "BLOCK"


class OpenItemType(StrEnum):
    SALES_INVOICE = "SALES_INVOICE"
    PURCHASE_INVOICE = "PURCHASE_INVOICE"
    CREDIT_NOTE = "CREDIT_NOTE"
    DEBIT_NOTE = "DEBIT_NOTE"
    OPENING_AR = "OPENING_AR"
    OPENING_AP = "OPENING_AP"
    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"
    SUPPLIER_PAYMENT = "SUPPLIER_PAYMENT"


class PaymentAllocationSource(StrEnum):
    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"
    SUPPLIER_PAYMENT = "SUPPLIER_PAYMENT"
    CREDIT_NOTE = "CREDIT_NOTE"
    DEBIT_NOTE = "DEBIT_NOTE"


class StockMovementType(StrEnum):
    PURCHASE = "PURCHASE"
    SALE = "SALE"
    IMPORT = "IMPORT"
    EXPORT = "EXPORT"
    TRANSFER_IN = "TRANSFER_IN"
    TRANSFER_OUT = "TRANSFER_OUT"
    RETURN_IN = "RETURN_IN"
    RETURN_OUT = "RETURN_OUT"
    ADJUSTMENT = "ADJUSTMENT"
    DAMAGE = "DAMAGE"
    OPENING_STOCK = "OPENING_STOCK"
    QC_HOLD = "QC_HOLD"
    QC_RELEASE = "QC_RELEASE"


class ShipmentType(StrEnum):
    IMPORT = "IMPORT"
    EXPORT = "EXPORT"
    DOMESTIC = "DOMESTIC"


class NotificationChannel(StrEnum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    SMS = "SMS"
    PUSH = "PUSH"


class ChatType(StrEnum):
    DM = "DM"
    GROUP = "GROUP"


class MeetingType(StrEnum):
    INTERNAL = "INTERNAL"
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"
    EXTERNAL = "EXTERNAL"


class TenantStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    CLOSED = "CLOSED"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INVITED = "INVITED"
    DISABLED = "DISABLED"


class AuditAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    SUBMIT = "SUBMIT"
    SEND = "SEND"
    ACCEPT = "ACCEPT"
    DECLINE = "DECLINE"
    CLONE = "CLONE"
    POST = "POST"
    CANCEL = "CANCEL"
    CONFIRM = "CONFIRM"
    ISSUE = "ISSUE"
    CLOSE = "CLOSE"
    CONVERT = "CONVERT"
    ACKNOWLEDGE = "ACKNOWLEDGE"
    REVISE = "REVISE"
    LINK = "LINK"
    UNLINK = "UNLINK"
    PACK = "PACK"
    DISPATCH = "DISPATCH"
    ARRIVE = "ARRIVE"
    REVERSE = "REVERSE"
    OVERRIDE = "OVERRIDE"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"


class AuditStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class BranchStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class EmployeeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class AddressType(StrEnum):
    BRANCH = "BRANCH"
    HEADQUARTERS = "HEADQUARTERS"
    BILLING = "BILLING"
    SHIPPING = "SHIPPING"
    WAREHOUSE = "WAREHOUSE"
    OTHER = "OTHER"


class AttachmentEntityType(StrEnum):
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"
    CONTACT = "CONTACT"
    PRODUCT = "PRODUCT"
    QUOTATION = "QUOTATION"
    SALES_ORDER = "SALES_ORDER"
    PURCHASE_ORDER = "PURCHASE_ORDER"
    BRANCH = "BRANCH"
    EMPLOYEE = "EMPLOYEE"
    STOCK_TRANSFER = "STOCK_TRANSFER"
    STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
    PROFORMA_INVOICE = "PROFORMA_INVOICE"
    GOODS_RECEIPT = "GOODS_RECEIPT"
    QUALITY_INSPECTION = "QUALITY_INSPECTION"
    PACKAGE = "PACKAGE"
    SHIPMENT = "SHIPMENT"
    SALES_INVOICE = "SALES_INVOICE"
    PURCHASE_INVOICE = "PURCHASE_INVOICE"
    CREDIT_NOTE = "CREDIT_NOTE"
    DEBIT_NOTE = "DEBIT_NOTE"
    DELIVERY_NOTE = "DELIVERY_NOTE"
    SALES_RETURN = "SALES_RETURN"
    JOURNAL_ENTRY = "JOURNAL_ENTRY"
    ACCOUNT = "ACCOUNT"
    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"
    SUPPLIER_PAYMENT = "SUPPLIER_PAYMENT"
    LANDED_COST = "LANDED_COST"


class AttachmentCategory(StrEnum):
    QC_PHOTO = "QC_PHOTO"
    TEST_CERTIFICATE = "TEST_CERTIFICATE"
    LOADING_PHOTO = "LOADING_PHOTO"
    SEAL_PHOTO = "SEAL_PHOTO"
    BL_DOCUMENT = "BL_DOCUMENT"
    CUSTOMS_DOC = "CUSTOMS_DOC"
    CUSTOMER_PO = "CUSTOMER_PO"
    SUPPLIER_INVOICE = "SUPPLIER_INVOICE"
    TRADE_LICENCE = "TRADE_LICENCE"
    POD = "POD"
    RETURN_PHOTO = "RETURN_PHOTO"
    PACKING_LIST = "PACKING_LIST"
    DISPATCH_PHOTO = "DISPATCH_PHOTO"
    PAYMENT_PROOF = "PAYMENT_PROOF"
    OTHER = "OTHER"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    DONE = "DONE"
    FAILED = "FAILED"
    DEAD = "DEAD"


class SortOrder(StrEnum):
    ASC = "asc"
    DESC = "desc"
